name: TheKingsFall
version: 0.1
author: SYTHM.
main: fr.tkf.plugin.Main
commands:
  heal:
    description: Heal the player.
    permission: heal.use
  team:
    description: Add player(s) to the specified team color.
    permission: team.use
    aliases: tm
  speed:
    description: Change the player speed
    permission: speed.use
  territory:
    description: Create or remove a territory
    permission: territory.use
    aliases: ter
  spectate:
    description: Spectate a player
    permission: spectate.use
    aliases: spec
api-version: 1.16
